import oracledb
from datetime import datetime

# Conexão com banco Oracle
conn = oracledb.connect(
     user='RM563145',
     password="260399",
     dsn='oracle.fiap.com.br:1521/ORCL'
)
cursor = conn.cursor()

# Criando as tabelas
cursor.execute("""
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE FAZENDA (
            id_fazenda NUMBER PRIMARY KEY,
            nome_fazenda VARCHAR2(100),
            loc_fazenda VARCHAR2(100),
            area_plantio FLOAT,
            unidade_medida_area VARCHAR2(20)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
""")

cursor.execute("""
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE CULTURAS (
            id_cultura NUMBER PRIMARY KEY,
            id_fazenda NUMBER,
            nome_cultura VARCHAR2(100),
            tipo_cultura VARCHAR2(100),
            area_cultura FLOAT,
            data_plantio DATE,
            data_colheita DATE,
            status_cultura VARCHAR2(50),
            FOREIGN KEY (id_fazenda) REFERENCES FAZENDA(id_fazenda)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
""")

cursor.execute("""
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE SENSOR_PH (
            id_senso_PH NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            id_cultura NUMBER,
            PH_registrado FLOAT,
            valor_PH FLOAT,
            variacao_PH FLOAT,
            data_hora TIMESTAMP,
            status_sensor VARCHAR2(50),
            loc_sensor VARCHAR2(100),
            FOREIGN KEY (id_cultura) REFERENCES CULTURAS(id_cultura)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
""")

conn.commit()

cursor.close()
conn.close()

