CREATE TABLE SENSOR_PH (
            id_sensor_PH NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            PH_registrado FLOAT,
            data_hora TIMESTAMP,
            status_sensor VARCHAR2(50),
            loc_sensor VARCHAR2(100)
            );
            
CREATE TABLE SENSOR_Fosforo (
            id_sensor_Fosforo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            Fosforo_registrado FLOAT,
            data_hora TIMESTAMP,
            status_sensor VARCHAR2(50),
            loc_sensor VARCHAR2(100)
        );
        
CREATE TABLE SENSOR_Potassio (
            id_sensor_Potassio NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            Potassio_registrado FLOAT,
            data_hora TIMESTAMP,
            status_sensor VARCHAR2(50),
            loc_sensor VARCHAR2(100)
        );
